# declare a default storage class that will be used to 
# dynamically provision general-purpose (gp2) EBS volumes for the Kubernetes PVs:
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: general
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2